export interface User {
    id: string,
    firstName:  string,
    lastName:   string,
    isSuperAdmin: boolean,
    isAdmin: boolean,
    email: string,
    phoneNumber: string,
    token: string,
    // isOfficer: boolean,
    // isTruckerHR: boolean,
    // isBanker: boolean,
    // isTrucker: boolean,
    // isSaver: boolean,
    // isLoaner: boolean,
    // isInvestor: boolean,
    // isDriver: boolean,
    // isMiner: boolean,
    // isSeller: boolean,
    // isRecruiter: boolean,
    
}
