language: node_js
node_js:
 - "10.9.0"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build --prod
after_success:
  - rm -r  ~/../var/www/Denov-Angular/
  - mv dist/Denov-Angular/ ~/../var/www


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on: